# PCA

In [1]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.decomposition import PCA

In [2]:
dataset = pd.read_csv("/home/alicja/Documents/ultimateData.csv")
dataset.set_index('label')

thiG  siaM  imuB  pbpC  dhbE  anmK  irtA  \
label                                                                
PSA-BAB-IMI-102140_14-1      3     3     3     3     2     2     2   
PSA-BAB-IMI-102140_lbl3      3     3     3     3     2     2     2   
PSA-BAB-IMI-102140_lkd16     3     3     3     3     2     2     2   
PSA-BAB-IMI-102140_lma1      3     3     3     3     2     2     2   
PSA-BAB-IMI-102140_luz19     3     3     3     3     2     2     2   
PSA-BAB-IMI-102140_luz24     3     3     3     3     2     2     2   
PSA-BAB-IMI-102140_luz7      3     3     3     3     2     2     2   
PSA-BAB-IMI-102140_pb1       3     3     3     3     2     2     2   
PSA-BAB-IMI-102141_14-1      3     3     3     3     2     2     1   
PSA-BAB-IMI-102141_lbl3      3     3     3     3     2     2     1   
PSA-BAB-IMI-102141_lkd16     3     3     3     3     2     2     1   
PSA-BAB-IMI-102141_lma1      3     3     3     3     2     2     1   
PSA-BAB-IMI-102141_luz19     3     3     3     3     2     2     1   
PSA-BAB-IMI-102141_luz24     3     3     3     3     2     2     1   
PSA-BAB-IMI-102141_luz7      3     3     3     3     2     2     1   
PSA-BAB-IMI-102141_pb1       3     3     3     3     2     2     1   
PSA-BAB-IMI-102143_14-1      3     3     3     3     2     3     2   
PSA-BAB-IMI-102143_lbl3      3     3     3     3     2     3     2   
PSA-BAB-IMI-102143_lkd16     3     3     3     3     2     3     2   
PSA-BAB-IMI-102143_lma1      3     3     3     3     2     3     2   
PSA-BAB-IMI-102143_luz19     3     3     3     3     2     3     2   
PSA-BAB-IMI-102143_luz24     3     3     3     3     2     3     2   
PSA-BAB-IMI-102143_luz7      3     3     3     3     2     3     2   
PSA-BAB-IMI-102143_pb1       3     3     3     3     2     3     2   
PSA-BAB-IMI-102177_14-1      3     3     3     3     2     2     1   
PSA-BAB-IMI-102177_lbl3      3     3     3     3     2     2     1   
PSA-BAB-IMI-102177_lkd16     3     3     3     3     2     2     1   
PSA-BAB-IMI-102177_lma1      3     3     3     3     2     2     1   
PSA-BAB-IMI-102177_luz19     3     3     3     3     2     2     1   
PSA-BAB-IMI-102177_luz24     3     3     3     3     2     2     1   
...                        ...   ...   ...   ...   ...   ...   ...   
PSA-TIM-IMI-101129_lkd16     3     3     3     3     2     2     2   
PSA-TIM-IMI-101129_lma1      3     3     3     3     2     2     2   
PSA-TIM-IMI-101129_luz19     3     3     3     3     2     2     2   
PSA-TIM-IMI-101129_luz24     3     3     3     3     2     2     2   
PSA-TIM-IMI-101129_luz7      3     3     3     3     2     2     2   
PSA-TIM-IMI-101129_pb1       3     3     3     3     2     2     2   
PSA-TIM-IMI-101131_14-1      3     3     3     3     2     2     2   
PSA-TIM-IMI-101131_lbl3      3     3     3     3     2     2     2   
PSA-TIM-IMI-101131_lkd16     3     3     3     3     2     2     2   
PSA-TIM-IMI-101131_lma1      3     3     3     3     2     2     2   
PSA-TIM-IMI-101131_luz19     3     3     3     3     2     2     2   
PSA-TIM-IMI-101131_luz24     3     3     3     3     2     2     2   
PSA-TIM-IMI-101131_luz7      3     3     3     3     2     2     2   
PSA-TIM-IMI-101131_pb1       3     3     3     3     2     2     2   
PSA-TIM-IMI-101132_14-1      3     3     3     3     2     2     3   
PSA-TIM-IMI-101132_lbl3      3     3     3     3     2     2     3   
PSA-TIM-IMI-101132_lkd16     3     3     3     3     2     2     3   
PSA-TIM-IMI-101132_lma1      3     3     3     3     2     2     3   
PSA-TIM-IMI-101132_luz19     3     3     3     3     2     2     3   
PSA-TIM-IMI-101132_luz24     3     3     3     3     2     2     3   
PSA-TIM-IMI-101132_luz7      3     3     3     3     2     2     3   
PSA-TIM-IMI-101132_pb1       3     3     3     3     2     2     3   
PSA-TIM-IMI-101133_14-1      3     3     3     3     2     2     2   
PSA-TIM-IMI-101133_lbl3      3     3     3     3     2     2     2   
PSA-TIM-IMI-101133_lkd16     3     3

In [3]:
labels = dataset['value'].values
features = dataset.drop('value', axis=1).values

In [4]:
features = features[:,1:].astype(np.float32)

In [5]:
dim_reduction = PCA(n_components=0.95)

In [14]:
dim_reduction.fit_transform(features)

array([[ 11.15723   ,  -1.7113537 ,  -0.55796367, ...,   0.33829615,
         -1.9063858 ,   1.1977547 ],
       [ 11.156284  ,  -1.7114019 ,  -0.5579453 , ...,   0.33829942,
         -1.9063902 ,   1.1977581 ],
       [ 11.156364  ,  -1.7112756 ,  -0.55793095, ...,   0.3383062 ,
         -1.9063978 ,   1.1977595 ],
       ...,
       [-23.222364  ,  -0.5829341 ,  -0.3955103 , ...,   1.8730979 ,
          1.329528  ,  -0.3852752 ],
       [-23.22236   ,  -0.58293355,  -0.3955412 , ...,   1.8730971 ,
          1.3295289 ,  -0.3852752 ],
       [-23.22243   ,  -0.58293355,  -0.39551878, ...,   1.8730952 ,
          1.3295393 ,  -0.38528436]], dtype=float32)

In [23]:
dim_reduction.components_[0]

array([-8.6592510e-04,  4.5133138e-04,  7.3118157e-05, ...,
        1.0561780e-07,  1.0561780e-07,  1.0442653e-07], dtype=float32)

In [11]:
dim_reduction.n_components_

222

In [13]:
dim_reduction.singular_values_

array([1175.696   ,  498.60962 ,  351.53528 ,  320.4251  ,  304.58466 ,
        300.27084 ,  287.91855 ,  267.21423 ,  252.94426 ,  244.96342 ,
        231.0127  ,  217.02834 ,  211.84856 ,  202.11687 ,  195.06104 ,
        190.84174 ,  178.26622 ,  176.04678 ,  170.11446 ,  168.70969 ,
        165.88965 ,  162.6965  ,  161.58318 ,  155.32835 ,  152.62338 ,
        149.79822 ,  147.09088 ,  142.94412 ,  137.4348  ,  137.25955 ,
        134.6847  ,  132.22299 ,  131.37206 ,  129.66576 ,  127.49984 ,
        126.18356 ,  124.61534 ,  121.49966 ,  119.86145 ,  118.80422 ,
        116.530334,  116.11195 ,  113.534   ,  112.87705 ,  111.18302 ,
        110.50742 ,  109.88264 ,  108.00489 ,  107.54302 ,  105.297646,
        104.30897 ,  103.96838 ,  103.79921 ,  103.12128 ,  102.60656 ,
        102.25068 ,  100.810844,  100.16838 ,   99.6628  ,   98.75988 ,
         98.650185,   97.495964,   96.60177 ,   96.29851 ,   95.48698 ,
         94.90633 ,   93.850624,   93.714134,   93.11596 ,   92.